2024-10-25 16:00:04 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_init&typeid=62&sort=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AFA11FA250>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2024-10-25 16:00:07 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_init&typeid=72&sort=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AFA1203BE0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2024-10-25 16:07:38 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_init&typeid=74&sort=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024513ECB5E0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2024-10-25 16:19:10 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=seoconfig&c=oauth&a=json_type&mode=sector (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D66EA03F40>, 'Connection to web.dajiti.com timed out. (connect timeout=5)'))
2024-10-25 16:39:55 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_RDS (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
2024-10-25 16:40:58 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=seoconfig&c=oauth&a=json_type&mode=sector (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000021965B21D60>, 'Connection to web.dajiti.com timed out. (connect timeout=5)'))
2024-10-25 19:42:39 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_RDS (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
2024-10-25 19:44:30 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_RDS (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
2024-10-25 19:44:46 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_RDS (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
2024-10-25 19:45:04 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_init&typeid=74&sort=1 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
2024-10-25 19:45:19 - HTTPSConnectionPool(host='web.dajiti.com', port=443): Max retries exceeded with url: /index.php?m=automatic&c=oauth&a=json_init&typeid=74&sort=1 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
